-- Crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbcurso
DEFAULT CHARACTER SET utf8;

-- Poner en uso la db
USE dbCURSO;

-- Crear la tabla PERSONA
(
CREATE table PERSONA
DNIPER CHAR(8)
NOMPER VARCHAR(80),
APEPER VARCHAR(80),
FECNAPER DATE,
CELPER CHAR(9),
SEXPER CHAR(1),
TIPPER CHAR(3),
DISTPER VARCHAR (80),
FECREGPER TIMESTAMP,
PWPER VARCHAR (20)
CONSTRAINT DNIPER_PK PRIMARY KEY (DNIPER)
);
-- Crear la tabla DEPARTAMENTO
CREATE TABLE DEPARTAMENTO
(
IDDEP INT,
NOMDEP VARCHAR(50) NOT NULL,
DNIPER CHAR(8),
SALJERFDEP DECIMAL(8,2),
CONSTRAINT IDDEP_PK PRIMARY KEY(IDDEP)
);

-- Relacionar la tabla PERSONA con DEPARTAMENTO
ALTER TABLE DEPARTAMENTO-- (NOMBRE DE LA TABLA A DONDE LLEGA LA RELACIÓN)
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER -- (NOMBRE DE LA RELACIÓN : t.delFK_campoderelación)
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER); -- (campo FK luego tabla y campo PK)

